name: Build & Deploy to GitHub Pages
on:
  push:
    branches: [main]     # run whenever main updates
permissions:
  contents: read
  pages: write
  id-token: write        # required for GitHub Pages
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20          # or whatever you use

      - run: npm ci
      - run: npm run build:static   # produces /out

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./out               # <-- key line
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
